version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_c
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  mysql:
    image: mysql:latest
    container_name: mysql_c
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    command: --local-infile=1

  mongo:
    image: mongo:latest
    container_name: mongo_c
    volumes:
      - mongo-data:/data/db
    ports:
      - "${MONGO_PORT}:27017"

  adminer:
    image: adminer
    container_name: adminer_c
    ports:
      - "${ADMINER_PORT}:8080"

volumes:
  postgres-data:
  mysql-data:
  mongo-data:
