services:
  ingesta-t_users:
    build: ./t_users
    volumes:
      - ~/.aws:/root/.aws:ro
  
  ingesta-t_favorites:
    build: ./t_favorites
    volumes:
      - ~/.aws:/root/.aws:ro
  
  ingesta-t_environments:
    build: ./t_environments
    volumes:
      - ~/.aws:/root/.aws:ro
  
  ingesta-t_books:
    build: ./t_books
    volumes:
      - ~/.aws:/root/.aws:ro
  