services:
  ingesta-clientes:
    build: ./clientes
    volumes:
      - ~/.aws:~/.aws:ro

  ingesta-movimientos:
    build: ./movimientos
    volumes:
      - ~/.aws:~/.aws:ro
  
  ingesta-productos:
    build: ./productos
    volumes:
      - ~/.aws:~/.aws:ro
