services:
  ingesta-t_users:
    container_name: t_users
    build:
      context: ./t_users
      args:
        STAGE: ${STAGE}
    volumes:
      - ~/.aws:/root/.aws:ro

  ingesta-t_favorites:
    container_name: t_favorites
    build:
      context: ./t_favorites
      args:
        STAGE: ${STAGE}
    volumes:
      - ~/.aws:/root/.aws:ro

  ingesta-t_environments:
    container_name: t_environments
    build:
      context: ./t_environments
      args:
        STAGE: ${STAGE}
    volumes:
      - ~/.aws:/root/.aws:ro

  ingesta-t_books:
    container_name: t_books
    build:
      context: ./t_books
      args:
        STAGE: ${STAGE}
    volumes:
      - ~/.aws:/root/.aws:ro
