services:
  ingesta-t_users:
    container_name: t_users
    build: ./t_users
    environment:
      - STAGE=${STAGE}
    volumes:
      - ~/.aws-credentials/eduardo:/root/.aws:ro
      - ./logs:/logs

  ingesta-t_favorites:
    container_name: t_favorites
    build: ./t_favorites
    environment:
      - STAGE=${STAGE}
    volumes:
      - ~/.aws-credentials/mikel:/root/.aws:ro
      - ./logs:/logs

  ingesta-t_environments:
    container_name: t_environments
    build: ./t_environments
    environment:
      - STAGE=${STAGE}
    volumes:
      - ~/.aws-credentials/gino:/root/.aws:ro
      - ./logs:/logs

  ingesta-t_books:
    container_name: t_books
    build: ./t_books
    environment:
      - STAGE=${STAGE}
    volumes:
      - ~/.aws-credentials/gino:/root/.aws:ro
      - ./logs:/logs

  ingesta-t_notifications:
    container_name: t_notifications
    build: ./t_notifications
    environment:
      - STAGE=${STAGE}
    volumes:
      - ~/.aws-credentials/quenta:/root/.aws:ro
      - ./logs:/logs

  ingesta-t_reservations:
    container_name: t_reservations
    build: ./t_reservations
    environment:
      - STAGE=${STAGE}
    volumes:
      - ~/.aws-credentials/mikel:/root/.aws:ro
      - ./logs:/logs