services:
  ingesta-clientes:
    build: ./clientes
    volumes:
      - ~/.aws:/root/.aws:ro

  ingesta-movimientos:
    build: ./movimientos
    volumes:
      - ~/.aws:/root/.aws:ro
  
  ingesta-productos:
    build: ./productos
    volumes:
      - ~/.aws:/root/.aws:ro
